name: conference_app
description: Flutter application to manage conference

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.6
  intl: 0.18.1
  path: 1.8.3
  built_value: 8.6.2
  built_collection: 5.1.1
  wc_form_validators: 1.0.0
  cached_network_image: 3.2.3
  after_layout: 1.2.0
  dio: 5.3.2
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  hydrated_bloc: 9.1.2
  flutter_i18n: 0.34.0
  flutter_translate_annotations: 2.1.0
  url_launcher: 6.1.14
  responsive_builder: 0.7.0
  path_provider: 2.1.1
  tuple: 2.0.2
  flutter_staggered_grid_view: 0.7.0
  timeago: 3.5.0
  socket_io_client: 2.0.3+1
  rxdart: 0.27.7
  file_picker: 5.5.0
  flutter_ringtone_player: 3.2.0
  firebase_core: 2.15.1
  firebase_crashlytics: 3.3.5
  firebase_messaging: 14.6.7
  transition: 2.0.2
  ansicolor: 2.0.1
  logging: 1.2.0
  timezone: 0.9.2
  flutter_dotenv: 5.1.0
  mobile_scanner: 3.3.0
  freezed_annotation: 2.4.1
  shared_preferences: 2.2.1
  image_picker: 1.0.4
  qr_flutter: 4.1.0
  package_info_plus: 4.1.0
  share_plus: 7.1.0
  universal_html: 2.2.3
  google_fonts: ^5.1.0
  dropdown_button2: ^2.3.9
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.5.0
  from_css_color: ^2.0.0
  go_router: ^10.1.2
  page_transition: ^2.0.9
  json_path: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.6
  flutter_lints: 2.0.3
  built_value_generator: 8.6.2
  flutter_translate_gen: 2.2.0
  freezed: 2.4.2

dependency_overrides:
  analyzer: 5.12.0

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/images/
    - assets/flutter_i18n/
    - assets/audios/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800

scripts: derry.yaml
